### ISSUE TITLE
Fix the root issue that's forcing the AJAX calls to use a kludge

### ISSUE THREAD

**Issue by 007noon700** [wustl-cerl/CRUD-Tutorial#16]
Get it so that it stops making the previous calls again but with the new form data.

**Comment by james-daily** [comment]
Here's a link to the code for reference:

https://github.com/wustl-cerl/CRUD-Tutorial/blob/04d809eed494e003804333863157332e3c1dad12/resources/views/songs/index.blade.php#L142
